spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb
    username: root
    password: 비밀번호입력
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
